export class SidebarNames{
    public static COMPONENT_NAVBAR_NAVIGATION =  'COMPONENT_NAVBAR_NAVIGATION';
    public static COMPONENT_CLIENT_DETAILS = 'COMPONENT_CLIENT_DETAILS';
    public static COMPONENT_CLIENT_FORM_UPDATE = 'COMPONENT_CLIENT_FORM_UPDATE';
    public static COMPONENT_CLIENT_FORM_CREATE = 'COMPONENT_CLIENT_FORM_CREATE';
}
