export class SidebarNames{
    public static COMPONENT_NAVBAR_NAVIGATION =  'COMPONENT_NAVBAR_NAVIGATION';
    public static COMPONENT_CLIENT_DETAILS = 'COMPONENT_CLIENT_DETAILS';
    public static COMPONENT_CLIENT_FORM = 'COMPONENT_CLIENT_FORM';
}
